[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ahash = "0.8.12"
dotenvy = "0.15.7"
itertools = "0.14.0"
nom = "8.0.0"
rand = "0.9.1"
regex = "1.11.1"
ureq = "3.0.12"